{
  imports = [
    ./nixvim.nix
    ./keymaps/keymaps.nix
    ./keymaps/no_yank_del.nix
    ./ui/colorscheme.nix
    ./ui/lualine.nix
    ./ui/noice.nix
    #./utils/telescope.nix
    ./utils/picker.nix
    ./utils/diagnostic.nix
    ./utils/flash.nix
    ./utils/lsp.nix
    ./utils/indentscope.nix
    ./utils/yazi.nix
    ./langmap.nix
    ./misc.nix
    ./options.nix
  ];
}
