{
  imports = [
    ./boot.nix
    ./configuration.nix
    ./hardware-configuration.nix
    ./kanata.nix
    ./packages.nix
    ./services.nix

    ../../modules/nixos/audio.nix
    ../../modules/nixos/cleanup.nix
    ../../modules/nixos/clipse.nix
    ../../modules/nixos/config.nix
    ../../modules/nixos/core/hardware.nix
    ../../modules/nixos/core/nix.nix
    ../../modules/nixos/core/nixpkgs.nix
    ../../modules/nixos/core/polkit.nix
    ../../modules/nixos/core/security.nix
    ../../modules/nixos/dev.nix
    ../../modules/nixos/font.nix
    ../../modules/nixos/fontconfig.nix
    ../../modules/nixos/gamemode.nix
    ../../modules/nixos/misc.nix
    ../../modules/nixos/mpd.nix
    ../../modules/nixos/nix-gaming.nix
    ../../modules/nixos/options.nix
    ../../modules/nixos/shared.nix
    ../../modules/nixos/steam.nix
    ../../modules/nixos/disk.nix
    ../../modules/nixos/stylix.nix
    ../../modules/nixos/wine.nix
    ../../modules/nixos/ydotool.nix

    ../../themes/blacchiato/nixos/default.nix
    ../../themes/everforest/nixos/default.nix
    ../../themes/lix/nixos/default.nix
    ../../themes/macchiato/nixos/default.nix
    ../../themes/kanso/nixos/default.nix
    ../../themes/kantsi/nixos/default.nix
  ];
}
