{
  imports = [
    ./themes/everforest/hard/hard.nix
    ./themes/everforest/medium/medium.nix
    ./themes/everforest/soft/soft.nix
    ./themes/everforest/soft/lualine.nix
    ./themes/everforest/medium/medium.nix
    ./themes/everforest/medium/lualine.nix
    ./themes/everforest/hard/hard.nix
    ./themes/everforest/hard/lualine.nix
    ./themes/black.nix
    ./themes/macchiato.nix
    # ./utils/picker.nix
    ./keymaps/keymaps.nix
    ./keymaps/no_yank_del.nix
    ./keymaps/langmap.nix
    ./lazy.nix
    ./misc.nix
    ./nixvim.nix
    ./options.nix
    ./ui/lualine.nix
    ./ui/noice.nix
    ./ui/zen-mode.nix
    ./utils/bracketed.nix
    ./ui/colorizer.nix
    ./utils/diagnostic.nix
    ./utils/completion.nix
    # ./utils/firenvim.nix
    ./utils/flash.nix
    ./utils/harpoon.nix
    ./utils/indentscope.nix
    ./utils/lsp.nix
    ./utils/pairs.nix
    ./utils/splitjoin.nix
    ./utils/surround.nix
    ./utils/telescope.nix
    ./utils/treesitter-textobjects.nix
    ./utils/treesitter.nix
    ./utils/yazi.nix
  ];
}
