# Theming
font: mononoki nerd font mono 16
background: "#00000000"
color: "#cad3f500"
border: "#b7bdf800"
separator: " ➜ "

border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: true

menu:
  - key: [ "q", "Mod4+q" ]
    desc: float active
    cmd: niri msg action quit

  - key: [ "s", "Mod4+s" ]
    desc: float active
    cmd: niri msg action screenshot -p false

  - key: [ "o", "Mod4+o" ]
    desc: kill window
    cmd: nu -e "let pid = niri msg --json pick-window | jq '.pid' | into int; kill \$pid"

  # - key: [ "p", "Mod4+p" ]
  #   desc: float active
  #   cmd: hex=$(niri msg pick-color | grep -o '#.*') && echo -n "$hex" | wl-copy && notify-send "$hex"

  - key: [ "p", "Mod4+p" ]
    desc: pick colour
    cmd: ~/nix/stuff/scripts/hextoimg.sh

  - key: [ "k", "Mod4+k" ]
    desc: float active
    cmd: systemctl restart kanata-lily-58

  - key: [ "f", "Mod4+f" ]
    desc: float active
    cmd: niri msg action toggle-window-floating

  - key: [ "c", "Mod4+c" ]
    desc: center column
    cmd: niri msg action center-column

  - key: [ "x", "Mod4+x" ]
    desc: expand column
    cmd: niri msg action expand-column-to-available-width

  - key: [ "m", "Mod4+m" ]
    desc: maximise column
    cmd: niri msg action maximize-column

  - key: [ "h", "Mod4+h" ]
    desc: first col
    cmd: niri msg action move-column-left

  - key: [ "i", "Mod4+i" ]
    desc: first col
    cmd: niri msg action move-column-right

  - key: [ "a", "Mod4+a" ]
    desc: first col
    cmd: niri msg action focus-column-first

  - key: [ "e", "Mod4+e" ]
    desc: last col
    cmd: niri msg action focus-column-last

  - key: [ "t", "Mod4+t" ]
    desc: last col
    cmd: niri msg action toggle-column-tabbed-display

