(use-package meow
  :config
  (defun meow-setup ()

    ;; Clear existing bindings
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("1" . meow-expand-1)
     '("2" . meow-expand-2)
     '("3" . meow-expand-3)
     '("4" . meow-expand-4)
     '("5" . meow-expand-5)
     '("6" . meow-expand-6)
     '("7" . meow-expand-7)
     '("8" . meow-expand-8)
     '("9" . meow-expand-9)
     ;; ... more numbered expand bindings
     ; '("y" . meow-left)
     '("a" . meow-next)
     '("e" . meow-prev)
     ; '("m" . meow-right)
     '("o" . meow-kill)
     '("l" . meow-yank)
     '("j" . meow-save)
     '("u" . meow-change)
     '("p" . meow-undo)
     '("/" . meow-visit)
     '("m" . meow-search)
     '("c" . meow-next-word)
     '("C" . meow-next-symbol)
     '("t" . meow-back-word)
     '("T" . meow-back-symbol)
     '("x" . meow-line)
     '("f" . meow-find)
     '("d" . meow-till)
     '("h" . meow-inner-of-thing)
     '("i" . meow-bounds-of-thing)
     '("H" . meow-beginning-of-thing)
     '("I" . meow-end-of-thing)
     '("n" . meow-insert)
     '("s" . meow-append)
     '("k" . meow-open-below)
     '("K" . meow-open-above)
     '(";" . meow-cancel-selection)
     '("C-;" . meow-pop-selection)
     '("<backspace>" . meow-delete)
     '("<escape>" . meow-cancel-selection)
     ; '("k" . meow-reverse)
     ))

(setq meow-char-thing-table
      '((?r . round)
        (?b . square)
        (?c . curly)
        (?a . angle)
        (?s . string)
        (?p . paragraph)
        (?l . line)
        (?f . buffer)))

(with-eval-after-load 'meow
  (add-to-list 'meow-expand-exclude-mode-list meow-normal-mode)
)

  (meow-setup)
  (meow-global-mode 1))

